---
- name: Deploy GitLab Server
  hosts: gitlab_server
  become: yes
  tasks:
    - name: Install dependencies
      apt:
        name: "{{ packages }}"
      vars:
        packages:
          - curl
          - openssh-server
          - ca-certificates
          - postfix
    - name: Download GitLab installation script
      get_url:
        url: https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh
        dest: /tmp/script.deb.sh
        mode: "0775"
    - name: Execute installation script
      command: /tmp/script.deb.sh
    - name: Install GitLab
      apt:
        name: gitlab-ce
        update_cache: yes
    - name: Download gitLab.rb
      get_url:
        url: https://gist.githubusercontent.com/Musubi42/eac9c10f7eff6faf8dcf5b3a7b61b113/raw/08cd3b9acb8cc3e8d17aeec846bbbf7212284c0c/gitlab.rb
        dest: /tmp/gitlab.rb
        mode: "0777"
    - name: Update /etc/gitlab/gitlab.rb
      command: mv /tmp/gitlab.rb /etc/gitlab/gitlab.rb
    - name: Reconfigure GitLab
      command: gitlab-ctl reconfigure