---
- name: Install MySQL 5.7
  hosts: database
  become: yes
  tasks:
    - name: Wait for /var/lib/dpkg/lock-frontend to be released 
      shell: while lsof /var/lib/dpkg/lock-frontend ; do sleep 10; done;
    - name: Install mysql
      apt:
        name:
          - mysql-server
          - mysql-client
          - python3-mysqldb
          - libmysqlclient-dev
        state: present
    - name: Start mysql
      service:
        name: mysql
        state: started
        enabled: yes
    - name: Create user
      mysql_user:
        name: user
        password: user
        host: '%'
        priv: '*.*:ALL'
        state: present
    - name: Ensure database is present
      community.mysql.mysql_db:
        name: "back"
        state: present
        login_user: "user"
        login_password: "user"
        login_host: "localhost"
    - name: Accept incoming
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '^bind-address'
        line: 'bind-address = 0.0.0.0'
        backup: yes
      notify: restart mysql
  handlers:
    - name: restart mysql
      service:
        name: mysql
        state: restarted