---
- name: Configure UFW Firewall
  hosts: gitlab_server
  become: yes
  tasks:
    - name: Install UFW
      apt:
        name: ufw
        update_cache: yes
    - name: Enable UFW
      ufw:
        state: enabled
        policy: deny
        direction: incoming
    - name: Allow SSH
      ufw:
        rule: allow
        name: OpenSSH
    - name: Allow HTTP
      ufw:
        rule: allow
        port: "80"
        proto: tcp
    - name: Allow HTTPS
      ufw:
        rule: allow
        port: "443"
        proto: tcp
      